name: CI/CD #Name of pipeline(It will be displayed in actions tab)

on: #On which all actions to run this workflow
  push: #Specifying action
    branches: #Specifying branch
      - master

jobs:
  build: #Build will run on where?
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code #Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python #Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies #Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Deploy #Deploy the web application
      #   if: success()
      #   run: |
      #     pip install gunicorn
      #     gunicorn -b 0.0.0.0:5000 app:app
      - shell : bash
        run : |
          expr 1+1 > output.log
      - name : Upload output file
        uses: actions/upload-artifact@v4
        with:  
          name: output-log-file
          path: output.log
          #COmmit
